2020-03-20 09:00:02,515 ERROR: Exception on /setCookie [POST] [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2241, in preprocess_request
    rv = func()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\routes.py", line 34, in before_request_func
    return redirect (url_for('setCookie'))
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'setCookie'. Did you mean 'setcookie' instead?
2020-03-20 09:01:32,541 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:02:14,634 ERROR: Exception on /setCookie [POST] [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2241, in preprocess_request
    rv = func()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\routes.py", line 34, in before_request_func
    return redirect (url_for('setCookie'))
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'setCookie'. Did you mean 'setcookie' instead?
2020-03-20 09:03:24,940 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:05:17,205 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:24:10,914 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:24:14,219 ERROR: Exception on / [GET] [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2241, in preprocess_request
    rv = func()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\routes.py", line 17, in before_request_func
    alert(document.cookie);
NameError: name 'alert' is not defined
2020-03-20 09:44:03,027 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:45:42,780 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:45:59,063 ERROR: Exception on / [GET] [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2241, in preprocess_request
    rv = func()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\routes.py", line 18, in before_request_func
    return redirect(url_for(shopLocation))
NameError: name 'shopLocation' is not defined
2020-03-20 09:47:17,247 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:49:54,692 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:51:05,244 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 09:55:12,392 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 10:02:05,213 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 10:17:13,803 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 10:18:05,304 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-20 10:21:14,829 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
